---
- hosts: shards
  remote_user: 'null'
  tasks:
  - name: start ssh-agent and add key
    shell: eval `ssh-agent`
  - name: add key to authorized_keys
    authorized_key:
      user: 'null'
      key: '{{item}}'
    with_file:
      - ~/.ssh/id_ed25519.pub
  - name: change authorized_keys permissions
    file:
      path: /home/null/.ssh/authorized_keys
      mode: 0600
