---
- hosts: shards
  vars:
    hostname: '{{ inventory_hostname }}'
  become: yes
  become_method: sudo
  tasks: 
    - name: change hostname
      hostname:
        name: '{{ hostname }}'
    - name: add hostname ipv4 to hosts file
      lineinfile:
        dest: /etc/hosts
        state: present
        regexp: '127.0.0.1   {{ hostname }}'
        line: '127.0.0.1   {{ hostname }}'
    - name: add hostname ipv6 to hosts file
      lineinfile:
        dest: /etc/hosts
        state: present
        regexp: '::1   {{ hostname }}'
        line: '::1   {{ hostname }}'
