---
- hosts: shards
  remote_user: 'null'
  become: yes
  tasks:
  - name: refresh apt cache
    apt:
      update_cache: yes
      state: latest
  - name: update software
    apt:
      state: latest
      name: '*'
  