---
- hosts: shards
  become: yes
  tasks:
  - name: get docker convenience script
    get_url:
      url: https://get.docker.com
      dest: /tmp/get-docker.sh
      mode: 0755
  - name: run docker convenience script
    script: /tmp/get-docker.sh
    args:
      executable: sh
  - name: create docker group
    group:
      name: docker
      system: yes
      state: present
  - name: add docker group to user
    user:
      name: 'null'
      groups: docker
      append: yes
      state: present
  - name: enable docker
    service: 
      name: docker
      enabled: yes
  - name: start docker
    service:
      name: docker
      state: started
  
  # - name: refresh apt cache
  #   apt:
  #     update_cache: yes
  #     state: latest
  # - name: install docker
  #   apt:
  #     name:
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io
  #     state: latest
  #   notify:
  #     - add docker group to user
  #     - enable docker
  #     - start docker
