---
- hosts: shards
  remote_user: root
  tasks:
  - name: make copy of sudoers file
    command: cp -f /etc/sudoers /etc/sudoers.tmp
  - name: make backup of sudoers file
    command: cp -f /etc/sudoers /etc/sudoers.bak
  - name: create admin group
    group:
      name: shard
      system: yes
      state: present
  - name: shard group can sudo
    lineinfile:
      dest: /etc/sudoers.tmp
      state: present
      regexp: '^%shard'
      line: '%shard ALL=(ALL) NOPASSWD:ALL'
  - name: ssh-agent works via sudo
    lineinfile:
      dest: /etc/sudoers.tmp
      state: present
      regexp: '^Defaults env_keep\+\=SSH_AUTH_SOCK'
      line: 'Defaults env_keep+=SSH_AUTH_SOCK'
  - name: create users
    user: 
      state: present
      name: 'null'
      groups: shard
      append: yes
      update_password: on_create
      password: '$6$Nug00YaTFIt2nzwE$6HRabrD6GCL36t2ic0CrxZ8bXYKWvIhauNUxDI8cdB9Sv5V9WCsHjMLE03WxkDJKprMA54ILJRWmrW/ouqADS1'
      ssh_key_type: 'ecdsa'
      ssh_key_bits: '256'
      generate_ssh_key: yes
  - name: updating sudoers
    shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  - name: start ssh-agent
    command: ssh-agent
    become: yes
    become_user: 'null'
  - name: add ssh key to ssh-agent
    command: ssh-add /home/null/.ssh/id_ecdsa
    become: yes
    become_user: 'null'
  - name: add key to authorized_keys
    authorized_key:
      user: 'null'
      key: '{{item}}'
    with_file:
      - /home/null/.ssh/id_ecdsa.pub
  - name: change authorized_keys permissions
    file:
      path: /home/null/.ssh/authorized_keys
      mode: 0600
  - name: retrieve ssh private keys
    fetch:
      fail_on_missing: yes
      validate_checksum: yes
      src: /home/null/.ssh/id_ecdsa
      dest: /home/void/.ssh/shards/
  - name: retrieve ssh public keys
    fetch:
      fail_on_missing: yes
      validate_checksum: yes
      src: /home/null/.ssh/id_ecdsa.pub
      dest: /home/void/.ssh/shards/
