---
- hosts: slaveshards
  remote_user: root
  tasks:
  - name: make copy of sudoers file
    command: cp -f /etc/sudoers /etc/sudoers.tmp
  - name: make backup of sudoers file
    command: cp -f /etc/sudoers /etc/sudoers.bak
  - name: create admin group
    group:
      name: shard
      system: yes
      state: present
  - name: shard group can sudo
    lineinfile:
      dest: /etc/sudoers.tmp
      state: present
      regexp: '^%shard'
      line: '%shard ALL=(ALL) NOPASSWD:ALL'
  - name: ssh-agent works via sudo
    lineinfile:
      dest: /etc/sudoers.tmp
      state: present
      regexp: '^Defaults env_keep\+\=SSH_AUTH_SOCK'
      line: 'Defaults env_keep+=SSH_AUTH_SOCK'
  - name: add group to users
    user: 
      state: present
      name: 'null'
      groups: shard
      append: yes
  - name: updating sudoers
    shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers