---
- hosts: shards
  become: yes
  become_method: sudo
  tasks:
  - name: add docker repo
    yum_repository:
      name: docker-ce
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
  - name: refresh yum cache
    yum:
      update_cache: yes
      state: latest
  - name: install neovim
    yum:
      name: neovim
      state: latest
  - name: install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
    notify:
      - enable docker
      - start docker
  handlers:
    - name: enable docker
      service: 
        name: docker
        enabled: yes
    - name: start docker
      service:
        name: docker
        state: started
        
