---
- hosts: slaveshards
  become: yes
  tasks:
  - name: install docker repo dependencies
    yum:
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: latest
  - name: get docker convenience script
    get_url: 
      url: https://get.docker.com
      dest: /tmp/get-docker.sh
      mode: 0655
  - name: run docker convenience script
    shell: /tmp/get-docker.sh
  - name: refresh yum cache
    yum:
      update_cache: yes
      state: latest
  - name: install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
    notify:
      - add docker group to user
      - enable docker
      - start docker
  handlers:
    - name: add docker group to user
      user:
        name: 'null'
        state: present
        groups: docker
        append: yes
    - name: enable docker
      service: 
        name: docker
        enabled: yes
    - name: start docker
      service:
        name: docker
        state: started
        
- hosts: mastershard
  become: yes
  tasks:
  # - name: get docker convenience script
  #   get_url: 
  #     url: https://get.docker.com
  #     dest: /tmp/get-docker.sh
  #     mode: 0655
  # - name: run docker convenience script
  #   shell: /tmp/get-docker.sh
  - name: refresh apt cache
    apt:
      update_cache: yes
      state: latest
  # - name: install neovim
  #   apt:
  #     name:
  #       - neovim
  #       - python3-neovim
  #       - python-neovim
  #     state: latest
  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
    notify:
      - add docker group to user
      - enable docker
      - start docker
  handlers:
    - name: add docker group to user
      user:
        name: 'null'
        state: present
        groups: docker
        append: yes
    - name: enable docker
      service: 
        name: docker
        enabled: yes
    - name: start docker
      service:
        name: docker
        state: started