---
- hosts: slaveshards
  become: yes
  tasks:
  - name: add docker repo
    yum_repository:
      name: docker-ce
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
  - name: refresh yum cache
    yum:
      update_cache: yes
      state: latest
  - name: install neovim
    yum:
      name: neovim
      state: latest
  - name: install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
    notify:
      - add docker group to user
      - enable docker
      - start docker
  handlers:
    - name: add docker group to user
      user:
        name: 'null'
        state: present
        groups: docker
        append: yes
    - name: enable docker
      service: 
        name: docker
        enabled: yes
    - name: start docker
      service:
        name: docker
        state: started
        
- hosts: mastershard
  become: yes
  tasks:
  - name: get docker convenience script
    shell: curl -fsSL https://get.docker.com -o /tmp/get_docker.sh
  - name: run docker convenience script
    shell: /tmp/get-docker.sh
  - name: refresh yum cache
    apt:
      update_cache: yes
      state: latest
  - name: install neovim
    apt:
      name: neovim
      state: latest
  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
    notify:
      - add docker group to user
      - enable docker
      - start docker
  handlers:
    - name: add docker group to user
      user:
        name: 'null'
        state: present
        groups: docker
        append: yes
    - name: enable docker
      service: 
        name: docker
        enabled: yes
    - name: start docker
      service:
        name: docker
        state: started