---
- hosts: slaveshards
  become: yes
  tasks:
  - name: refresh yum cache
    yum:
      update_cache: yes
      state: latest
  - name: update software
    yum:
      state: latest
      name: '*'

- hosts: mastershard
  become: yes
  tasks:
  - name: refresh apt cache
    apt:
      update_cache: yes
      state: latest
  - name: update software
    apt:
      state: latest
      name: '*'
  